//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.17 at 10:56:06 ���� CST 
//


package org.codeidiot.cityadvstory;






/**
 * <p>Java class for DialogType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DialogType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Trigger"/>
 *     &lt;enumeration value="Near"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */


public enum DialogType {


    /**
     * ������ʽ���Ի��������ͨ���ά���RFID���������NPC�ĶԻ�
     * 
     */

    TRIGGER("Trigger"),

    /**
     * ����δʵ�֣���·��ʽ���Ի�������Ҿ����NPCһ�����벢�������NPCʱ����Ի�
     * 
     */

    NEAR("Near");
    private final String value;

    DialogType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DialogType fromValue(String v) {
        for (DialogType c: DialogType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
