//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.17 at 10:56:06 ���� CST 
//


package org.codeidiot.cityadvstory;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.codeidiot.cityadvstory package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory implements java.io.Serializable {
private static final long serialVersionUID = 1L;



    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.codeidiot.cityadvstory
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Conditions.TaskCondition }
     * 
     */
    public Conditions.TaskCondition createConditionsTaskCondition() {
        return new Conditions.TaskCondition();
    }

    /**
     * Create an instance of {@link CityAdvStory }
     * 
     */
    public CityAdvStory createCityAdvStory() {
        return new CityAdvStory();
    }

    /**
     * Create an instance of {@link CityAdvStory.Tasks.Task }
     * 
     */
    public CityAdvStory.Tasks.Task createCityAdvStoryTasksTask() {
        return new CityAdvStory.Tasks.Task();
    }

    /**
     * Create an instance of {@link Conditions.InputCondition }
     * 
     */
    public Conditions.InputCondition createConditionsInputCondition() {
        return new Conditions.InputCondition();
    }

    /**
     * Create an instance of {@link CityAdvStory.NPCs.NPC.Dialog }
     * 
     */
    public CityAdvStory.NPCs.NPC.Dialog createCityAdvStoryNPCsNPCDialog() {
        return new CityAdvStory.NPCs.NPC.Dialog();
    }

    /**
     * Create an instance of {@link TaskTriggerPoint }
     * 
     */
    public TaskTriggerPoint createTaskTriggerPoint() {
        return new TaskTriggerPoint();
    }

    /**
     * Create an instance of {@link CityAdvStory.Tasks }
     * 
     */
    public CityAdvStory.Tasks createCityAdvStoryTasks() {
        return new CityAdvStory.Tasks();
    }

    /**
     * Create an instance of {@link Conditions }
     * 
     */
    public Conditions createConditions() {
        return new Conditions();
    }

    /**
     * Create an instance of {@link Conditions.EventPointCondition }
     * 
     */
    public Conditions.EventPointCondition createConditionsEventPointCondition() {
        return new Conditions.EventPointCondition();
    }

    /**
     * Create an instance of {@link CityAdvStory.NPCs.NPC }
     * 
     */
    public CityAdvStory.NPCs.NPC createCityAdvStoryNPCsNPC() {
        return new CityAdvStory.NPCs.NPC();
    }

    /**
     * Create an instance of {@link Conditions.SelectionCondition }
     * 
     */
    public Conditions.SelectionCondition createConditionsSelectionCondition() {
        return new Conditions.SelectionCondition();
    }

    /**
     * Create an instance of {@link CityAdvStory.NPCs }
     * 
     */
    public CityAdvStory.NPCs createCityAdvStoryNPCs() {
        return new CityAdvStory.NPCs();
    }

}
