//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.17 at 10:56:06 ���� CST 
//


package org.codeidiot.cityadvstory;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TaskConditionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TaskConditionType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="NotTaken"/>
 *     &lt;enumeration value="Doing"/>
 *     &lt;enumeration value="Completed"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TaskConditionType")
@XmlEnum
public enum TaskConditionType {


    /**
     * ��û�нӵ�ָ��������
     * 
     */
    @XmlEnumValue("NotTaken")
    NOT_TAKEN("NotTaken"),

    /**
     * ָ�����������ڽ���
     * 
     */
    @XmlEnumValue("Doing")
    DOING("Doing"),

    /**
     * ָ���������Ѿ����
     * 
     */
    @XmlEnumValue("Completed")
    COMPLETED("Completed");
    private final String value;

    TaskConditionType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TaskConditionType fromValue(String v) {
        for (TaskConditionType c: TaskConditionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
