//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.17 at 10:56:06 ���� CST 
//


package org.codeidiot.cityadvstory;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Tasks" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="Task">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Start" type="{http://www.codeidiot.org/CityAdvStory/}TaskTriggerPoint"/>
 *                             &lt;element name="End" type="{http://www.codeidiot.org/CityAdvStory/}TaskTriggerPoint"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="Title" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="Id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="NPCs" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="NPC">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                             &lt;element name="Dialog">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Conditions" type="{http://www.codeidiot.org/CityAdvStory/}Conditions" minOccurs="0"/>
 *                                       &lt;element name="Content" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="Type" type="{http://www.codeidiot.org/CityAdvStory/}DialogType" default="Trigger" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="EventPoint" use="required" type="{http://www.codeidiot.org/CityAdvStory/}EventPointName" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tasks",
    "npCs"
})
@XmlRootElement(name = "CityAdvStory")
public class CityAdvStory implements java.io.Serializable {
private static final long serialVersionUID = 1L;


    @XmlElement(name = "Tasks")    protected CityAdvStory.Tasks tasks;
    @XmlElement(name = "NPCs")    protected CityAdvStory.NPCs npCs;

    /**
     * Gets the value of the tasks property.
     * 
     * @return
     *     possible object is
     *     {@link CityAdvStory.Tasks }
     *     
     */
    public CityAdvStory.Tasks getTasks() {
        return tasks;
    }

    /**
     * Sets the value of the tasks property.
     * 
     * @param value
     *     allowed object is
     *     {@link CityAdvStory.Tasks }
     *     
     */
    public void setTasks(CityAdvStory.Tasks value) {
        this.tasks = value;
    }

    /**
     * Gets the value of the npCs property.
     * 
     * @return
     *     possible object is
     *     {@link CityAdvStory.NPCs }
     *     
     */
    public CityAdvStory.NPCs getNPCs() {
        return npCs;
    }

    /**
     * Sets the value of the npCs property.
     * 
     * @param value
     *     allowed object is
     *     {@link CityAdvStory.NPCs }
     *     
     */
    public void setNPCs(CityAdvStory.NPCs value) {
        this.npCs = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="NPC">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *                   &lt;element name="Dialog">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Conditions" type="{http://www.codeidiot.org/CityAdvStory/}Conditions" minOccurs="0"/>
     *                             &lt;element name="Content" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                           &lt;attribute name="Type" type="{http://www.codeidiot.org/CityAdvStory/}DialogType" default="Trigger" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="EventPoint" use="required" type="{http://www.codeidiot.org/CityAdvStory/}EventPointName" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "npc"
    })
    public static class NPCs implements java.io.Serializable {
private static final long serialVersionUID = 1L;


        @XmlElement(name = "NPC")
        protected List<CityAdvStory.NPCs.NPC> npc;

        /**
         * Gets the value of the npc property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the npc property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getNPC().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CityAdvStory.NPCs.NPC }
         * 
         * 
         */
        public List<CityAdvStory.NPCs.NPC> getNPC() {
            if (npc == null) {
                npc = new ArrayList<CityAdvStory.NPCs.NPC>();
            }
            return this.npc;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
         *         &lt;element name="Dialog">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Conditions" type="{http://www.codeidiot.org/CityAdvStory/}Conditions" minOccurs="0"/>
         *                   &lt;element name="Content" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *                 &lt;attribute name="Type" type="{http://www.codeidiot.org/CityAdvStory/}DialogType" default="Trigger" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="EventPoint" use="required" type="{http://www.codeidiot.org/CityAdvStory/}EventPointName" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "dialog"
        })
        public static class NPC implements java.io.Serializable {
private static final long serialVersionUID = 1L;


            @XmlElement(name = "Dialog")
            protected List<CityAdvStory.NPCs.NPC.Dialog> dialog;
            @XmlAttribute(name = "Name", required = true)
            protected String name;
            @XmlAttribute(name = "EventPoint", required = true)
            protected String eventPoint;

            /**
             * Gets the value of the dialog property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the dialog property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDialog().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link CityAdvStory.NPCs.NPC.Dialog }
             * 
             * 
             */
            public List<CityAdvStory.NPCs.NPC.Dialog> getDialog() {
                if (dialog == null) {
                    dialog = new ArrayList<CityAdvStory.NPCs.NPC.Dialog>();
                }
                return this.dialog;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the eventPoint property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEventPoint() {
                return eventPoint;
            }

            /**
             * Sets the value of the eventPoint property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEventPoint(String value) {
                this.eventPoint = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Conditions" type="{http://www.codeidiot.org/CityAdvStory/}Conditions" minOccurs="0"/>
             *         &lt;element name="Content" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *       &lt;attribute name="Type" type="{http://www.codeidiot.org/CityAdvStory/}DialogType" default="Trigger" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "conditions",
                "content"
            })
            public static class Dialog implements java.io.Serializable {
private static final long serialVersionUID = 1L;


                @XmlElement(name = "Conditions")
                protected Conditions conditions;
                @XmlElement(name = "Content", required = true)
                protected String content;
                @XmlAttribute(name = "Type")
                protected DialogType type;

                /**
                 * Gets the value of the conditions property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Conditions }
                 *     
                 */
                public Conditions getConditions() {
                    return conditions;
                }

                /**
                 * Sets the value of the conditions property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Conditions }
                 *     
                 */
                public void setConditions(Conditions value) {
                    this.conditions = value;
                }

                /**
                 * Gets the value of the content property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getContent() {
                    return content;
                }

                /**
                 * Sets the value of the content property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setContent(String value) {
                    this.content = value;
                }

                /**
                 * Gets the value of the type property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link DialogType }
                 *     
                 */
                public DialogType getType() {
                    if (type == null) {
                        return DialogType.TRIGGER;
                    } else {
                        return type;
                    }
                }

                /**
                 * Sets the value of the type property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link DialogType }
                 *     
                 */
                public void setType(DialogType value) {
                    this.type = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="Task">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Start" type="{http://www.codeidiot.org/CityAdvStory/}TaskTriggerPoint"/>
     *                   &lt;element name="End" type="{http://www.codeidiot.org/CityAdvStory/}TaskTriggerPoint"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="Title" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="Id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "task"
    })
    public static class Tasks implements java.io.Serializable {
private static final long serialVersionUID = 1L;


        @XmlElement(name = "Task")
        protected List<CityAdvStory.Tasks.Task> task;

        /**
         * Gets the value of the task property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the task property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTask().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CityAdvStory.Tasks.Task }
         * 
         * 
         */
        public List<CityAdvStory.Tasks.Task> getTask() {
            if (task == null) {
                task = new ArrayList<CityAdvStory.Tasks.Task>();
            }
            return this.task;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Start" type="{http://www.codeidiot.org/CityAdvStory/}TaskTriggerPoint"/>
         *         &lt;element name="End" type="{http://www.codeidiot.org/CityAdvStory/}TaskTriggerPoint"/>
         *       &lt;/sequence>
         *       &lt;attribute name="Title" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="Id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "start",
            "end"
        })
        public static class Task implements java.io.Serializable {
private static final long serialVersionUID = 1L;


            @XmlElement(name = "Start", required = true)
            protected TaskTriggerPoint start;
            @XmlElement(name = "End", required = true)
            protected TaskTriggerPoint end;
            @XmlAttribute(name = "Title", required = true)
            protected String title;
            @XmlAttribute(name = "Id", required = true)
            protected String id;

            /**
             * Gets the value of the start property.
             * 
             * @return
             *     possible object is
             *     {@link TaskTriggerPoint }
             *     
             */
            public TaskTriggerPoint getStart() {
                return start;
            }

            /**
             * Sets the value of the start property.
             * 
             * @param value
             *     allowed object is
             *     {@link TaskTriggerPoint }
             *     
             */
            public void setStart(TaskTriggerPoint value) {
                this.start = value;
            }

            /**
             * Gets the value of the end property.
             * 
             * @return
             *     possible object is
             *     {@link TaskTriggerPoint }
             *     
             */
            public TaskTriggerPoint getEnd() {
                return end;
            }

            /**
             * Sets the value of the end property.
             * 
             * @param value
             *     allowed object is
             *     {@link TaskTriggerPoint }
             *     
             */
            public void setEnd(TaskTriggerPoint value) {
                this.end = value;
            }

            /**
             * Gets the value of the title property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTitle() {
                return title;
            }

            /**
             * Sets the value of the title property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTitle(String value) {
                this.title = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

        }

    }

}
