//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.17 at 10:56:06 ���� CST 
//


package org.codeidiot.cityadvstory;








/**
 * <p>Java class for TaskTriggerPoint complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TaskTriggerPoint">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Conditions" type="{http://www.codeidiot.org/CityAdvStory/}Conditions" minOccurs="0"/>
 *         &lt;element name="PositiveDialog" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NegativeDialog" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="EventPoint" use="required" type="{http://www.codeidiot.org/CityAdvStory/}EventPointName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */


public class TaskTriggerPoint implements java.io.Serializable {
private static final long serialVersionUID = 1L;


    
    protected Conditions conditions;
    
    protected String positiveDialog;
    
    protected String negativeDialog;
    
    protected String eventPoint;

    /**
     * Gets the value of the conditions property.
     * 
     * @return
     *     possible object is
     *     {@link Conditions }
     *     
     */
    public Conditions getConditions() {
        return conditions;
    }

    /**
     * Sets the value of the conditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Conditions }
     *     
     */
    public void setConditions(Conditions value) {
        this.conditions = value;
    }

    /**
     * Gets the value of the positiveDialog property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPositiveDialog() {
        return positiveDialog;
    }

    /**
     * Sets the value of the positiveDialog property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPositiveDialog(String value) {
        this.positiveDialog = value;
    }

    /**
     * Gets the value of the negativeDialog property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNegativeDialog() {
        return negativeDialog;
    }

    /**
     * Sets the value of the negativeDialog property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNegativeDialog(String value) {
        this.negativeDialog = value;
    }

    /**
     * Gets the value of the eventPoint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventPoint() {
        return eventPoint;
    }

    /**
     * Sets the value of the eventPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventPoint(String value) {
        this.eventPoint = value;
    }

}
